[package]
name = "pr_notifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gjson = "0.8"
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"